#!/bin/bash

####  GENERAL SETTINGS  ####
#set mod to super key
# Window title/bar font. Bar can be overridden.
font pango:monospace 10
bar {
	#hidden bar shows on mod keypress
	mode hide
        status_command i3status 
	font pango:monospace 10
}
#focus/mouse options
focus_follows_mouse no
#map capsLock to control
setxkbmap -option caps:ctrl_modifier

#### CONFIG VARS ####
set $resizeSml 	1 px or 1 ppt
set $resizeMed 	5 px or 5 ppt
set $resizeLrg 	20 px or 20 ppt
set $resizeXLg 	100 px or 100 ppt
set $volSm 	1%
set $volMd 	5%
set $volLg 	20%

#### PROGRAMS ####
set $displays 		arandr
set $calculator 	qalculate
set $file-man 		ranger
set $pass-man 		keepassx
set $term 		gnome-terminal
set $text-editor 	vim
set $volume 		amixer set Master 
set $volume-interface 	amixer set Master 

#### BUTTON COMBOS ####
set $mod  		Mod4
set $modA 		Mod4+Mod1
set $modC 		Mod4+Control
set $modS 		Mod4+Shift
set $modAC 		Mod4+Mod1+Control
set $modAS 		Mod4+Mod1+Shift
set $modCS 		Mod4+Control+Shift
set $modACS 		Mod4+Mod1+Control+Shift

####  FUNCTION KEYS  ####
# audio buttons
bindsym XF86AudioMute			exec amixer set Master toggle
bindsym $mod+XF86AudioMute		exec $term -e $volume-interface
bindsym XF86AudioRaiseVolume		exec $volume $volMd+
bindsym XF86AudioLowerVolume 		exec $volume $volMd-
bindsym Control+XF86AudioRaiseVolume	exec $volume $volSm+
bindsym Control+XF86AudioLowerVolume	exec $volume $volSm-
bindsym Shift+XF86AudioRaiseVolume	exec $volume $volLg+
bindsym Shift+XF86AudioLowerVolume	exec $volume $volLg-

##~~ SUPER (launcher)
#~ #	- Go to workspace #
bindsym $mod+1		workspace 1
bindsym $mod+2		workspace 2
bindsym $mod+3		workspace 3
bindsym $mod+4		workspace 4
bindsym $mod+5		workspace 5
bindsym $mod+6		workspace 6
bindsym $mod+7		workspace 7
bindsym $mod+8		workspace 8
bindsym $mod+9		workspace 9
bindsym $mod+0		workspace 10
#~ spc	- System search (program name)
bindsym $mod+space	exec dmenu_run
#~ -	- New windows open up to the right.
bindsym $mod+minus	split v
#~ |	- New windows open up downward.
bindsym $mod+bar	split h
#~ a	- 
#~ b	- 
#~ c	- Calculator
bindsym $mod+c		exec $calculator
#~ d	- Displays
bindsym $mod+d		exec $displays
#~ e	- Text editor (vim)
bindsym $mod+e		exec $term -e $text-editor
#~ f	- File manager (ranger)
bindsym $mod+f		exec $term -e $file-man
#~ g	- Games (Not yet written. Does nothing.)
#~ h	- Help (Not yet written. Does nothing.)
#~ i	- 
#~ j	- 
#~ k	- 
#~ l	- 
#~ m	- Music
#~ n	- 
#~ o	- 
#~ p	- Password Manager
bindsym $mod+p 		exec $pass-man
#~ q	- 
#~ r	- 
#~ s	- 
#~ t	- Terminal
bindsym $mod+t		exec $term
bindsym $modA+t		exec $term
#~ u	- 
#~ v	- Video Player
#~ w	- Web browser
bindsym $mod+w		exec firefox
#~ x	- 
#~ y	- 
#~ z	- 

##~~ SHIFT+SUPER (window management)
#~ yuio	- Resize focused window by one unit
bindsym $modS+y		resize shrink width $resizeSml
bindsym $modS+u		resize shrink height $resizeSml
bindsym $modS+i		resize grow height $resizeSml
bindsym $modS+o		resize grow width $resizeSml
#~ Add the following keys to modify the increment unit to the following:
#~ ctl = 5, alt = 20, ctl+alt = 100
#ctl
bindsym $modCS+y	resize shrink width $resizeMed
bindsym $modCS+u	resize shrink height $resizeMed
bindsym $modCS+i	resize grow height $resizeMed
bindsym $modCS+o	resize grow width $resizeMed
#alt
bindsym $modAS+y	resize shrink width $resizeLrg
bindsym $modAS+u	resize shrink height $resizeLrg
bindsym $modAS+i	resize grow height $resizeLrg
bindsym $modAS+o	resize grow width $resizeLrg
#clt+alt
bindsym $modACS+y	resize shrink width $resizeXLg
bindsym $modACS+u	resize shrink height $resizeXLg
bindsym $modACS+i	resize grow height $resizeXLg
bindsym $modACS+o	resize grow width $resizeXLg
#~ hjkl - Move focus
bindsym $modS+h		focus left
bindsym $modS+j		focus down
bindsym $modS+k		focus up
bindsym $modS+l		focus right
#~ nm,. - Move active window position
bindsym $modS+n		move left
bindsym $modS+m		move down
bindsym $modS+comma	move up
bindsym $modS+period	move right
#~ #	- Move focused window to workspace #
bindsym $modS+1		move container to workspace 1
bindsym $modS+2		move container to workspace 2
bindsym $modS+3		move container to workspace 3
bindsym $modS+4		move container to workspace 4
bindsym $modS+5		move container to workspace 5
bindsym $modS+6		move container to workspace 6
bindsym $modS+7		move container to workspace 7
bindsym $modS+8		move container to workspace 8
bindsym $modS+9		move container to workspace 9
bindsym $modS+0		move container to workspace 10
# pc	- Toggle tiling / floating on active window
bindsym $modS+space	floating toggle
#~ -	- New windows open up to the right.
bindsym $modS+minus	split v
#~ |	- New windows open up downward.
bindsym $modS+bar	split h
#~ a		- 
#~ b	- 
#~ c	- 
#~ d	- 
#~ e	- 
#~ f	- 
#~ g	- 
#~ p	- 
#~ q	- Kill active window
bindsym $modS+q		kill
#~ r	- Refresh i3config
bindsym $modS+r		restart
#~ s	- Change layout to stacking
bindsym $modS+s		layout stacking
#~ t	- Change layout to tabbed
bindsym $modS+t		layout tabbed
#~ v	- Change layout to Verticle Split (You can also use - and |)
bindsym $modS+v		split v
#~ w	- 
#~ x	- 
#~ z	- 

##~~ CONTROL+SUPER (System commands)
#~ a	- 
#~ b	- 
#~ c	- 
#~ d	- 
#~ e 	- End i3 session (log out)
bindsym $modC+e		exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"
#~ f	- 
#~ g	- 
#~ h	- 
#~ i	- 
#~ j	- 
#~ k	- 
#~ l	- Lock screen
bindsym $modC+l		exec "c=$(shuf ~/.personalPreferences/favoriteColors | head -1 | cut -f2); i3lock --color $c"
#~ m	- 
#~ n	- 
#~ o	- 
#~ p	- 
#~ q	- 
#~ r	- Reload the i3 configuration file.
bindsym $modC+r		reload
#~ R	- Restart i3.
bindsym $modCS+r	restart
#~ s	- 
#~ t	- 
#~ u	- 
#~ v	- 
#~ w	- 
#~ x	- 
#~ y	- 
#~ z	- 

