#!/usr/bin/python3
import readline
from py3Tools.textCompleter import TextCompleter

# Create functions that optionsDict can point to
def terminal_urxvt():
	Xresources = open('/home/gun/.Xresources', 'r')
	for line in Xresources:
		if '!-' in line:
			#remove '!-' from beginning of line
			outputLine = line[2:]
			#remove trailing \n from line
			outputLine = outputLine.rstrip()
			print(outputLine)	
def i3():
	print("Please refer to the i3 config file located at ~/.config/i3/config\nAlternatively, you can enter super+h if the i3help script is installed correctly. The help script should probably be replaced and called in this script someday, somehow. I'm gonna make it alright but not right now.")

# Define options
optionsDict = {"terminal_urxvt":terminal_urxvt, "i3":i3}
optionsList = list(optionsDict.keys())

#set up the completer
completer = TextCompleter(optionsList)
readline.set_completer(completer.complete)
readline.parse_and_bind('tab: complete')

input = input("Select a package or topic of which you require assistance: ")
print ("You entered", input)
optionsDict[input]()
